Document: eye-on-manga
Title: Debian eye-on-manga Manual
Author: <insert document author here>
Abstract: This manual describes what eye-on-manga is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eye-on-manga/eye-on-manga.sgml.gz

Format: postscript
Files: /usr/share/doc/eye-on-manga/eye-on-manga.ps.gz

Format: text
Files: /usr/share/doc/eye-on-manga/eye-on-manga.text.gz

Format: HTML
Index: /usr/share/doc/eye-on-manga/html/index.html
Files: /usr/share/doc/eye-on-manga/html/*.html

  
